In [57]:
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt
import time

In [3]:
def sep_two_classes(Y, num_class):
    Y = Y.copy()
    for i in range(Y.shape[0]):
        if Y[i] == num_class:
            Y[i] = 1
        else:
            Y[i] = -1
    return Y

In [4]:
def h(theta, X):
    return 1.0 / (1 + np.exp(-np.dot(X, theta)))

In [5]:
def weak_clssefier(X, weights):
    Z = h(weights, X)
    return Z

In [54]:
def train_clf(X, Y, weights):
    newY = np.asarray([y if y == 1 else 0 for y in Y])
    P = np.asarray(h(weights, X))
    L = 0
    _accuracy = 0
    alpha = 0.001
    t = 0
    while t < 10:
        for i in range(len(weights)):
            weights[i] -= alpha * sum([(P[j] - newY[j])*X[j][i] for j in range(len(P))])
        P = h(weights, X)
        _accuracy = accuracy(newY, [0 if p < 0.5 else 1 for p in P])
        alpha = max(0.0001, alpha*0.9)
        if _accuracy > 0.5:
            return weights
        t+=1
    return weights

In [7]:
def Q(X, Y, W, weights_for_weak_clf):
    Qsum = 0
    for i in range(X.shape[0]):
        p = -1 if weak_clssefier(X[i], weights_for_weak_clf) < 0.5 else 1
        I = 1 if (Y[i]*p) < 0 else 0
        Qsum += W[i] * I
    return Qsum

In [8]:
def alpha(Q):
    return 0.5 * np.log((1-Q)/Q)

In [89]:
def fit(X, Y, num_weak_clf, T):
    #1 инициализация весов объектов
    num1 = 0
    for l in Y:
        if l == 1:
            num1 +=1
    
    P = np.asarray([1/num1 if y == 1 else 1/(Y.shape[0] - num1) for y in range(Y.shape[0])])
    alphas = []
    bs = []
    #2 Для всех t=1,...,T, пока не выполнен критерий останова.
    while len(alphas) < num_weak_clf:
        weights_for_weak_cls = np.random.rand(T, X.shape[1])#инициализируем матрицу с весами для слабых классификаторов,
        print(weights_for_weak_cls)
                        #выберем тот, у которого самые хорошие веса
        #print('WFCLS', weights_for_weak_cls)
        #2.1 Находим классификатор b_t: X->{-1,+1} который минимизирует взвешенную ошибку классификации;
        #b_t = argmin_b Q(b,W^l);
        for wfwc in weights_for_weak_cls:
            wfwc = train_clf(X, Y, wfwc)
        Qs = []
        for wfwc in weights_for_weak_cls:
            Qs.append(Q(X, Y, P, wfwc))
        Qs = np.asarray(Qs)
        argmin = np.argmin(Qs)
        if Qs[argmin]> 0.5:
            pass
        else:
            b_t_weights = weights_for_weak_cls[argmin]
            bs.append(b_t_weights)
            #2.2 Пересчитываем кооэффициент взвешенного голосования для алгоритма классификации b_t:

            alpha_t = alpha(Qs[argmin])
            alphas.append(alpha_t)

            #2.3 Пересчет весов объектов: w_i = w_i*exp(-alpha_t*y_i*b_t(x_i)), i = 1,...,l
            for i in range(P.shape[0]):
                p = -1 if weak_clssefier(X[i], b_t_weights) < 0.5 else 1
                P[i] *= np.exp(-alpha_t*Y[i]*p)

            #2.4 Нормировка весов объектов:

            P0 = np.sum(P)
            for p in P:
                p/=P0
    return np.asarray(alphas), np.asarray(bs)
        

In [10]:
def predict(X, alphas, weak_clf_weights):
    tmp_sum = 0
    for t in range(alphas.shape[0]):
        p = -1 if weak_clssefier(X, weak_clf_weights[t]) < 0.5 else 1
        tmp_sum += alphas[t] * p
    return (np.sign(tmp_sum), tmp_sum)

In [11]:
def accuracy(y_true, y_pred):
    counter = 0
    for i in range(len(y_true)):
        if y_true[i] == y_pred[i]:
            counter +=1
    return counter/len(y_true)

In [78]:
def plot_progress(X, Y, alphas, bs):
    progress = [0,]
    for i in range(0, len(alphas[0])):
        ttl = []
        for x in X:
            pr0 = predict(x, alphas[0][0:i], bs[0][0:i, :])
            pr1 = predict(x, alphas[1][0:i], bs[1][0:i, :])
            pr2 = predict(x, alphas[2][0:i], bs[2][0:i, :])
            ttl.append(np.argmax(np.asarray([pr0[1], pr1[1], pr2[1]])))
        progress.append(accuracy(Y, ttl))
    plt.plot(progress)
    plt.yticks(np.arange(0, 1.0, 0.1))
    plt.show()

In [13]:
iris = datasets.load_iris()
X, Y = iris.data, iris.target
p=np.random.permutation(X.shape[0])
x_train = X[p[0:int(len(X)*0.7)], :]
y_train = Y[p[0:int(len(Y)*0.7)]]
x_test = X[p[int(len(X)*0.7):], :]
y_test = Y[p[int(len(Y)*0.7):]]
x_train = (x_train - np.mean(x_train, axis = 0)) / np.var(x_train, axis = 0)
x_test = (x_test - np.mean(x_test, axis = 0)) / np.var(x_test, axis = 0)

y_train0 = sep_two_classes(y_train, 0)
y_train1 = sep_two_classes(y_train, 1)
y_train2 = sep_two_classes(y_train, 2)

y_test0 = sep_two_classes(y_test, 0)
y_test1 = sep_two_classes(y_test, 1)
y_test2 = sep_two_classes(y_test, 2)

In [ ]:
accuracys0 = np.asarray([])
accuracys1 = np.asarray([])
accuracys2 = np.asarray([])
total_accs = np.asarray([])
np.random.seed(0)
num_wclfs = 5
print('\n\n\n----------------------------------------------')
start_time = time.time()
alphas0, bs0 = fit(x_train, y_train0, num_wclfs, 15)
alphas1, bs1 = fit(x_train, y_train1, num_wclfs, 15)
alphas2, bs2 = fit(x_train, y_train2, num_wclfs, 15)
print("--- %s seconds ---" % (time.time() - start_time))

plot_progress(x_test, y_test, [alphas0, alphas1, alphas2], [bs0, bs1, bs2])
y_predicted0 = []
y_predicted1 = []
y_predicted2 = []
total_pr = []
for x in x_test:
    pr0 = predict(x, alphas0, bs0)
    pr1 = predict(x, alphas1, bs1)
    pr2 = predict(x, alphas2, bs2)
    y_predicted0.append(pr0[0])
    y_predicted1.append(pr1[0])
    y_predicted2.append(pr2[0])
    total_pr.append(np.argmax(np.asarray([pr0[1], pr1[1], pr2[1]])))

y_predicted0 = np.asarray(y_predicted0)
y_predicted1 = np.asarray(y_predicted1)
y_predicted2 = np.asarray(y_predicted2)
total_pr = np.asarray(total_pr)

acc0 = accuracy(y_test0, y_predicted0)
acc1 = accuracy(y_test1, y_predicted1)
acc2 = accuracy(y_test2, y_predicted2)
total_acc = accuracy(y_test, total_pr)

np.append(accuracys0, acc0)
np.append(accuracys1, acc1)
np.append(accuracys2, acc2)
np.append(total_accs, total_acc)
print('accurecy: {T} weak clfs'.format(T=num_wclfs), '\n 0:|{acc0}| \n 1:|{acc1}| \n 2:|{acc2}| \n total:|{total_acc}| \n'.format(acc0=acc0, acc1=acc1, acc2=acc2, total_acc=total_acc))




----------------------------------------------
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]
 [0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892]
 [0.52184832 0.41466194 0.26455561 0.77423369]
 [0.45615033 0.56843395 0.0187898  0.6176355 ]
 [0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547]
 [0.66676672 0.67063787 0.21038256 0.1289263 ]
 [0.31542835 0.36371077 0.57019677 0.43860151]
 [0.98837384 0.10204481 0.20887676 0.16130952]
 [0.65310833 0.2532916  0.46631077 0.24442559]]
[[0.15896958 0.11037514 0.65632959 0.13818295]
 [0.19658236 0.36872517 0.82099323 0.09710128]
 [0.83794491 0.09609841 0.97645947 0.4686512 ]
 [0.97676109 0.60484552 0.73926358 0.03918779]
 [0.28280696 0.12019656 0.2961402  0.11872772]
 [0.31798

[[2.35834224e-01 6.20499900e-01 6.39622243e-01 9.48540301e-01]
 [7.78276167e-01 8.48345270e-01 4.90419908e-01 1.85348587e-01]
 [9.95815293e-01 1.29355761e-01 4.71457319e-01 6.80930992e-02]
 [9.43850857e-01 9.64924941e-01 7.19389062e-01 3.49992844e-01]
 [2.54382401e-01 2.65303325e-01 1.27294025e-01 5.25808953e-01]
 [1.41817276e-01 3.16730667e-01 6.26706476e-01 7.27543610e-01]
 [2.42727046e-02 4.30115984e-01 6.52124595e-01 8.53245976e-01]
 [4.75324782e-01 9.69205872e-01 2.65632548e-01 1.35087066e-02]
 [4.83752865e-01 2.56113795e-01 8.23717672e-01 2.32772672e-01]
 [3.10629218e-01 7.91227431e-01 7.15143252e-01 5.58051237e-01]
 [7.04948062e-01 4.18636864e-01 5.31004761e-03 1.13551285e-02]
 [5.11221788e-01 8.32909797e-02 5.10754802e-02 9.65516639e-01]
 [8.59002640e-01 1.52027227e-01 6.64218590e-04 9.41667795e-01]
 [2.78325298e-01 1.85897603e-01 6.91508108e-01 1.08903739e-01]
 [2.64649598e-01 9.75094680e-01 6.39462774e-01 5.20677791e-01]]
[[0.39791861 0.77450095 0.14095748 0.9673378 ]
 [0.861

[[6.01943698e-01 6.33690045e-02 4.09857450e-01 7.22500088e-01]
 [2.38738841e-01 9.43827589e-01 6.86783368e-01 2.87575383e-01]
 [7.68998923e-01 8.31647718e-02 9.74774423e-01 4.92852591e-02]
 [9.33455891e-01 2.52853878e-01 7.57824108e-01 7.36994331e-05]
 [2.54240089e-01 7.49100607e-01 5.32336071e-01 1.14952150e-01]
 [3.93629746e-01 3.75549355e-01 5.68162244e-01 6.67977072e-01]
 [8.40830242e-01 4.97231397e-01 3.92021717e-01 1.43976534e-01]
 [8.04822965e-01 7.13370405e-01 4.08677397e-01 5.18432310e-01]
 [6.65182844e-01 1.64805590e-01 2.71977944e-02 3.17503699e-01]
 [5.95585020e-01 4.86606091e-01 6.92554627e-01 8.19689806e-01]
 [4.88442467e-01 1.34267024e-01 8.50628000e-01 5.74990327e-01]
 [7.39937481e-01 7.04664654e-01 9.68211771e-01 2.95307322e-01]
 [7.05306773e-01 3.65676333e-01 3.95410721e-01 2.30594637e-01]
 [3.44010176e-01 9.48296752e-01 2.92570847e-01 2.45990606e-01]
 [5.83137978e-01 2.58035957e-01 4.73385726e-01 8.34176257e-01]]
[[0.23040031 0.42669141 0.61048974 0.54562892]
 [0.974

[[0.4139625  0.6296183  0.77858426 0.85155779]
 [0.81641271 0.16607709 0.82838955 0.05862906]
 [0.20017068 0.62292672 0.11469253 0.6033476 ]
 [0.30796569 0.42946659 0.3151515  0.07017357]
 [0.50075875 0.96359944 0.61178335 0.30003187]
 [0.95614983 0.38923725 0.69751773 0.6341128 ]
 [0.95291085 0.91460269 0.14800406 0.08568587]
 [0.80964233 0.90494321 0.4929736  0.69076127]
 [0.06978828 0.2198044  0.14937619 0.60116058]
 [0.19753989 0.05984632 0.30220728 0.67721243]
 [0.57786372 0.33072497 0.83347888 0.27626911]
 [0.26054764 0.55994741 0.47821564 0.44597266]
 [0.15578562 0.50464619 0.25901892 0.39217988]
 [0.73357045 0.93686283 0.77386297 0.40563389]
 [0.59303314 0.74649782 0.41422105 0.36024816]]
[[0.1352433  0.7362608  0.83850859 0.31658441]
 [0.78350777 0.61021306 0.78408305 0.41133738]
 [0.74757636 0.40850912 0.08875799 0.55057892]
 [0.45432873 0.25287989 0.89211333 0.38285331]
 [0.03912611 0.38213574 0.42450981 0.86163772]
 [0.79918321 0.19996659 0.83902923 0.24792723]
 [0.34193415

[[3.96905539e-01 1.82951940e-01 8.77940510e-01 8.24077224e-01]
 [7.74959895e-01 5.72900385e-02 5.56719442e-01 2.35013562e-01]
 [1.19685197e-01 7.81613100e-01 2.11581375e-01 5.00811698e-01]
 [5.26096348e-01 2.13282004e-01 4.92261166e-01 5.28198976e-02]
 [7.24496385e-05 8.80321932e-01 4.15588702e-01 9.07419799e-01]
 [4.96307360e-01 4.31108295e-01 2.95912141e-01 8.16889376e-02]
 [3.09694649e-01 6.08470265e-01 7.62786347e-01 5.40825518e-01]
 [7.58255844e-01 1.57751592e-01 5.83239932e-01 8.82603227e-01]
 [2.17960208e-01 2.27668938e-01 7.48432513e-01 8.12056785e-01]
 [2.48046330e-01 3.31569804e-01 6.31769400e-01 3.98431713e-01]
 [6.24010970e-01 4.96430032e-01 7.73651309e-01 8.45888647e-01]
 [8.63827209e-01 6.11525078e-01 6.12584105e-01 4.49646899e-01]
 [2.76140450e-02 2.99180219e-01 6.36977185e-02 4.37785249e-01]
 [8.49485249e-01 5.96802018e-01 6.75532598e-01 1.88007972e-01]
 [2.61953150e-01 1.63132153e-01 8.42688762e-01 2.80313013e-01]]
[[0.56232631 0.14112861 0.12398891 0.34758336]
 [0.330

[[0.40991804 0.96251229 0.55282236 0.43171166]
 [0.95059885 0.09161385 0.27178199 0.34639444]
 [0.85350262 0.76641198 0.30471417 0.87256336]
 [0.06255667 0.49346694 0.65468424 0.31219431]
 [0.06917107 0.25716031 0.48377177 0.31810636]
 [0.41567186 0.09312462 0.01427354 0.87761265]
 [0.07811175 0.29282458 0.66404537 0.84450443]
 [0.32126274 0.6520685  0.47213129 0.05101303]
 [0.408363   0.02984805 0.9641903  0.7621838 ]
 [0.33929233 0.23474043 0.40032717 0.31616446]
 [0.37079441 0.91871443 0.40452514 0.74139949]
 [0.15681302 0.53368108 0.49373396 0.59123195]
 [0.67988749 0.86101944 0.22996725 0.38153411]
 [0.05718279 0.62418128 0.93475991 0.39619711]
 [0.97175108 0.59787524 0.21124671 0.52952903]]
[[0.64004555 0.66627283 0.63804181 0.18961397]
 [0.20831059 0.24146305 0.73299392 0.49935452]
 [0.67125557 0.79936341 0.56406952 0.47114104]
 [0.4025151  0.53626287 0.14957848 0.7864455 ]
 [0.91275924 0.81236504 0.82189557 0.82940141]
 [0.17564912 0.99581273 0.65718579 0.42092706]
 [0.88802385

[[0.2602528  0.48086882 0.42277839 0.45813251]
 [0.03031093 0.63307411 0.45096558 0.01678872]
 [0.93921334 0.19770042 0.16958959 0.75509405]
 [0.34866315 0.61154838 0.00596614 0.43143389]
 [0.02483401 0.20956185 0.19471741 0.97092676]
 [0.30241309 0.83925139 0.42075658 0.86212933]
 [0.66278723 0.00709242 0.11160023 0.03134501]
 [0.09044505 0.22031407 0.78558269 0.73368063]
 [0.24471356 0.39042294 0.85948794 0.07232116]
 [0.56481576 0.11502806 0.99405473 0.44164615]
 [0.91527128 0.15298271 0.99030617 0.05930393]
 [0.05892232 0.82323714 0.77659224 0.24793679]
 [0.24684592 0.47265508 0.94360254 0.62588653]
 [0.83252966 0.86710342 0.13444939 0.57880853]
 [0.98694078 0.09564527 0.44354644 0.76485332]]
[[0.98957706 0.1197161  0.4044393  0.75296056]
 [0.59407994 0.87865307 0.10214669 0.54251256]
 [0.60919391 0.81426454 0.84562256 0.47416506]
 [0.60432491 0.00785273 0.68902902 0.01544607]
 [0.64708837 0.50589605 0.95405972 0.16307401]
 [0.38377673 0.85729755 0.51409537 0.81462434]
 [0.50742545

[[0.55903986 0.02768987 0.76608825 0.71419022]
 [0.71725958 0.20721323 0.07028271 0.99728442]
 [0.47779723 0.72624274 0.09641738 0.50493226]
 [0.50409666 0.12285801 0.35160764 0.89146334]
 [0.69021493 0.7316708  0.87828879 0.3102856 ]
 [0.7899447  0.09653872 0.57754873 0.53414808]
 [0.4311922  0.20916916 0.42752651 0.84428314]
 [0.73070337 0.44060323 0.96758868 0.78529192]
 [0.04426062 0.75073652 0.71853778 0.04922066]
 [0.92655727 0.46703886 0.2391275  0.44822579]
 [0.83378047 0.25050582 0.91409279 0.06473981]
 [0.08935708 0.59932406 0.50979696 0.67150508]
 [0.04344593 0.26024237 0.70314468 0.34440157]
 [0.30465467 0.81977696 0.79606306 0.74499094]
 [0.62762542 0.95440514 0.021057   0.1526431 ]]
[[0.45988828 0.28068984 0.29335934 0.98029627]
 [0.04422048 0.02589787 0.93514486 0.16009004]
 [0.04297728 0.45854528 0.88189057 0.30606474]
 [0.93225145 0.86527615 0.28041788 0.43543919]
 [0.92373807 0.12328678 0.06189334 0.1887196 ]
 [0.22562127 0.17938901 0.03171207 0.71765893]
 [0.16195195

[[9.13699973e-01 6.13442734e-01 6.27191295e-01 7.48403055e-01]
 [9.36070609e-01 9.82477010e-01 4.92684875e-01 9.45007834e-01]
 [3.59242641e-01 7.27644802e-01 9.36795685e-01 1.62327774e-02]
 [9.20543242e-01 8.85050113e-01 2.05485803e-01 4.09713600e-01]
 [1.22919643e-01 7.47186807e-01 7.77413560e-01 8.80941920e-01]
 [4.41451961e-01 6.30061490e-01 8.43647520e-01 9.33783172e-02]
 [1.19158168e-01 8.17784653e-01 4.41969474e-01 8.02869388e-01]
 [1.50381081e-04 1.15028080e-01 3.68343264e-01 3.97657201e-01]
 [8.33757881e-01 5.09782498e-01 9.17964534e-01 4.24697706e-01]
 [6.69638526e-02 4.57962045e-01 4.11008784e-01 5.49457252e-01]
 [6.39829154e-01 5.89044704e-02 6.17529433e-01 1.32273670e-01]
 [4.31813184e-01 8.92330173e-01 1.33836528e-01 2.08759507e-01]
 [4.23018763e-01 6.03938712e-02 2.86276614e-01 7.74691278e-02]
 [4.77043621e-01 5.73378725e-01 7.49282356e-01 9.23239380e-01]
 [4.37620894e-01 6.27809952e-01 6.00682909e-02 4.75313828e-01]]
[[0.87000736 0.59227869 0.37510141 0.08924627]
 [0.498

[[0.28297932 0.32522514 0.49396892 0.73120047]
 [0.01495998 0.47821737 0.12349014 0.85322782]
 [0.25977675 0.40400343 0.04742345 0.14914279]
 [0.00178979 0.36003531 0.81068781 0.57577845]
 [0.83990615 0.1754583  0.67734155 0.74585756]
 [0.34400089 0.11429768 0.74220276 0.52147053]
 [0.46973132 0.83711004 0.49290613 0.29497546]
 [0.74843173 0.26984719 0.27628549 0.20873479]
 [0.10338732 0.8015756  0.70068493 0.38321319]
 [0.72498447 0.96124578 0.4662486  0.48828536]
 [0.52906075 0.26656018 0.24800406 0.48838472]
 [0.50073046 0.28928197 0.58231293 0.77079135]
 [0.68957864 0.14710847 0.64239177 0.00341829]
 [0.39269677 0.46102785 0.79555679 0.88009389]
 [0.71819772 0.77525225 0.93161379 0.48454715]]
[[2.79720215e-01 3.70140886e-01 4.28623842e-01 3.16153248e-01]
 [3.03714139e-01 9.82689844e-01 9.92326891e-01 6.42928092e-01]
 [8.09793836e-01 7.21144853e-01 6.82111727e-01 1.46508191e-01]
 [1.36721807e-01 8.85839863e-01 1.42671272e-02 6.79763879e-01]
 [8.04785339e-01 7.17913038e-01 1.44409263

[[0.41330767 0.22432512 0.64609907 0.3773027 ]
 [0.23917515 0.84392134 0.70294511 0.47164868]
 [0.28593539 0.8722931  0.41938382 0.46539673]
 [0.19199302 0.83392043 0.54990507 0.65689775]
 [0.41881723 0.01937738 0.30051182 0.02067216]
 [0.02992854 0.98512843 0.09474671 0.45099689]
 [0.83871949 0.42155039 0.2487523  0.41400158]
 [0.82388887 0.04489142 0.48877783 0.19350597]
 [0.06026933 0.78555448 0.01448252 0.41495795]
 [0.54550278 0.17288373 0.89945665 0.40868058]
 [0.1821038  0.61117957 0.63944869 0.38867143]
 [0.03146836 0.66164597 0.23776663 0.14992559]
 [0.82093714 0.50424141 0.44792976 0.75484224]
 [0.47068921 0.61183985 0.40624059 0.88752228]
 [0.56556564 0.90251105 0.89882957 0.75857073]]
[[0.54805129 0.65421959 0.22208486 0.91912736]
 [0.85973592 0.78714329 0.02548102 0.19452715]
 [0.91669741 0.80905393 0.84615962 0.4045695 ]
 [0.25637473 0.89069782 0.37295532 0.29887058]
 [0.30086231 0.88243239 0.17693005 0.83295734]
 [0.47756773 0.26114374 0.58423124 0.27899149]
 [0.51488868

[[0.25744458 0.13270752 0.57089608 0.92134213]
 [0.64880231 0.66386042 0.85842386 0.70012105]
 [0.37594043 0.80332511 0.12399737 0.87146894]
 [0.50914186 0.54582145 0.9226756  0.68267989]
 [0.07816848 0.25290603 0.7107665  0.09312105]
 [0.26129676 0.26368709 0.70770857 0.05162329]
 [0.34498114 0.42637293 0.0732928  0.45840154]
 [0.53140773 0.97081855 0.87351818 0.93055319]
 [0.27072997 0.15016724 0.63849236 0.20152488]
 [0.58648209 0.19572483 0.06514403 0.4489242 ]
 [0.6364498  0.09413467 0.54971804 0.43683489]
 [0.25524189 0.17187788 0.23432595 0.89661154]
 [0.03187045 0.14748451 0.51816987 0.68264092]
 [0.41031969 0.24035783 0.27434743 0.64939861]
 [0.71290182 0.97028564 0.70350781 0.42191547]]
[[0.24553952 0.53463877 0.72656619 0.11659202]
 [0.0598092  0.22415824 0.41924732 0.66717442]
 [0.00914363 0.53855627 0.29087467 0.3350155 ]
 [0.43322995 0.46002479 0.40178055 0.08739308]
 [0.15914371 0.49335937 0.38655678 0.99670168]
 [0.7696195  0.58285127 0.54783506 0.04999599]
 [0.67673153

[[0.68603472 0.50872127 0.61411062 0.98099492]
 [0.44179634 0.69796838 0.85942924 0.10450827]
 [0.58133997 0.45857241 0.99217471 0.9369735 ]
 [0.18620379 0.09760492 0.45363834 0.01915172]
 [0.49696336 0.73844258 0.88326674 0.96323816]
 [0.91687801 0.91394484 0.33487298 0.38658658]
 [0.81421408 0.46714628 0.15056139 0.45426863]
 [0.36991971 0.08532226 0.35041305 0.95922061]
 [0.92647412 0.96913802 0.57168277 0.10589506]
 [0.22698835 0.18636537 0.18865358 0.88834289]
 [0.20401771 0.37896548 0.09306691 0.03650799]
 [0.94785075 0.76241519 0.43489384 0.16881672]
 [0.98040389 0.43416327 0.54455391 0.0754238 ]
 [0.27954336 0.26233393 0.13902397 0.8941844 ]
 [0.19381916 0.03080259 0.9858598  0.93957357]]
[[0.72294647 0.84144096 0.15623987 0.0799775 ]
 [0.86421751 0.35848471 0.32277627 0.6886951 ]
 [0.7570406  0.61368574 0.09528787 0.36527263]
 [0.01315773 0.09745944 0.7283704  0.27260455]
 [0.15962039 0.9804556  0.82035487 0.6821466 ]
 [0.3255954  0.16778305 0.81610286 0.9265394 ]
 [0.86369406

[[0.15467223 0.86558456 0.48078991 0.15993754]
 [0.91717854 0.72358785 0.25401098 0.87653275]
 [0.73795196 0.99468639 0.07883995 0.61949069]
 [0.26029916 0.15257178 0.28996367 0.72681177]
 [0.62871668 0.31371608 0.10464182 0.12381701]
 [0.61020891 0.47508158 0.37087935 0.09674867]
 [0.49335249 0.26471    0.87360575 0.69400141]
 [0.41743298 0.91951368 0.55904984 0.82914444]
 [0.59337463 0.94324938 0.08882618 0.77800108]
 [0.04145047 0.10728537 0.80812818 0.72615354]
 [0.59478774 0.91643667 0.39540394 0.00545631]
 [0.07165412 0.72401856 0.25937051 0.58515815]
 [0.43962181 0.23213763 0.74346916 0.03045403]
 [0.68660317 0.7491665  0.08351471 0.27950349]
 [0.92395922 0.46350358 0.58325688 0.77383455]]
[[0.85531194 0.10299631 0.53271117 0.20643749]
 [0.69377041 0.94424175 0.04684355 0.64568768]
 [0.64171239 0.41470892 0.6271447  0.38987227]
 [0.986998   0.47987155 0.82489919 0.92970694]
 [0.74120515 0.67507784 0.70387299 0.12927517]
 [0.27218717 0.45745592 0.42389894 0.16275174]
 [0.32282351

[[0.82954967 0.290981   0.66593198 0.60776743]
 [0.39747531 0.54206356 0.52790007 0.06482289]
 [0.17956225 0.54556741 0.0435031  0.81013718]
 [0.39235216 0.07561348 0.84136304 0.06859416]
 [0.16852994 0.76666377 0.93365892 0.03459106]
 [0.06049779 0.48262743 0.41988345 0.96340748]
 [0.44742935 0.71030749 0.3503984  0.18426557]
 [0.68956607 0.45526437 0.56924333 0.80465526]
 [0.35343882 0.49251924 0.50685374 0.06828589]
 [0.68751267 0.44387778 0.59916378 0.88695574]
 [0.26223227 0.6736873  0.55757996 0.54107101]
 [0.93648455 0.35908876 0.06832994 0.34227889]
 [0.00613547 0.82262039 0.98893437 0.81279056]
 [0.79381264 0.64522507 0.57551369 0.56778956]
 [0.40532334 0.17330188 0.65285085 0.02517767]]
[[0.23175773 0.00423864 0.4991745  0.35643671]
 [0.42711893 0.57334204 0.07605003 0.26279074]
 [0.23001616 0.88632844 0.74123944 0.18589367]
 [0.8383495  0.4927272  0.81245789 0.73158463]
 [0.36166174 0.60175823 0.59952837 0.92006797]
 [0.09616708 0.83954242 0.39362658 0.14059623]
 [0.28613434

[[4.46119186e-01 8.77699672e-01 7.80287342e-01 7.56006265e-01]
 [2.51873035e-01 5.04025317e-02 2.17201397e-02 6.69637962e-01]
 [9.90248673e-01 7.45810931e-01 3.46467559e-01 6.72867298e-02]
 [4.76138974e-01 6.40883819e-01 4.58448970e-01 8.10730652e-01]
 [1.90141334e-01 8.87348100e-01 6.83028389e-01 9.76743571e-01]
 [3.05854863e-01 7.83123488e-01 3.30879173e-01 5.22944807e-01]
 [2.87196595e-01 1.03276671e-01 1.22900650e-01 3.66197382e-01]
 [1.49962096e-02 9.36497531e-01 5.24767887e-01 3.80066941e-01]
 [9.40896698e-01 7.33710361e-01 3.11691086e-01 5.94031313e-01]
 [5.55274877e-01 4.09288107e-01 5.78463575e-03 8.61379088e-01]
 [5.57025125e-01 1.12274803e-01 2.30551414e-01 3.33112063e-01]
 [3.24073081e-01 2.48751123e-01 9.73044371e-04 5.89990067e-02]
 [5.69730925e-01 5.49314020e-01 7.10669054e-01 6.03276091e-01]
 [1.88103929e-01 5.40566422e-01 7.61399767e-01 1.79208542e-02]
 [5.73155100e-01 6.83044870e-01 6.74122936e-02 3.14726710e-01]]
[[0.17838322 0.5724104  0.8252405  0.83829785]
 [0.161

[[0.93191024 0.15612787 0.71642773 0.56644261]
 [0.56412285 0.53022111 0.08851486 0.16253565]
 [0.34093212 0.41074817 0.02038229 0.03693136]
 [0.09371394 0.06565686 0.93267282 0.21915236]
 [0.96060752 0.07309468 0.82970486 0.59032961]
 [0.3997659  0.51113411 0.9933917  0.1476475 ]
 [0.45059107 0.98992075 0.64420259 0.99047411]
 [0.11300111 0.15220392 0.28461117 0.63130115]
 [0.31121419 0.62935332 0.05057692 0.22276605]
 [0.44223485 0.47280298 0.45543663 0.53295429]
 [0.41775544 0.90341879 0.80630092 0.42294245]
 [0.82215799 0.78450402 0.53719004 0.56694119]
 [0.47927382 0.55033868 0.51007433 0.27610559]
 [0.33946435 0.97437761 0.97263574 0.07449039]
 [0.840479   0.84473952 0.65787646 0.91151828]]
[[0.93803356 0.35804058 0.93322294 0.38717009]
 [0.4193876  0.54307245 0.9016539  0.31755714]
 [0.66398876 0.40193374 0.65885493 0.83359592]
 [0.32875318 0.23673417 0.87984555 0.39703699]
 [0.69733635 0.59550783 0.81226642 0.05097729]
 [0.12092097 0.45202225 0.17937865 0.50205434]
 [0.32294824

[[0.5606745  0.38336892 0.28763942 0.73531451]
 [0.20885333 0.11589757 0.82118462 0.05342826]
 [0.08563109 0.43693862 0.99980145 0.1070395 ]
 [0.37945057 0.0988906  0.44118413 0.34134749]
 [0.62821048 0.9560388  0.19718934 0.67978489]
 [0.94861909 0.79831654 0.86554158 0.42002871]
 [0.9729049  0.23260083 0.18087339 0.93805012]
 [0.33757367 0.51707252 0.72554099 0.99522593]
 [0.16508546 0.77728781 0.25369706 0.37301347]
 [0.54977038 0.09952989 0.90172455 0.47270498]
 [0.47228277 0.47047738 0.08639705 0.17395667]
 [0.27857737 0.58771037 0.99611151 0.36768406]
 [0.8482498  0.01379858 0.77308253 0.46148976]
 [0.66616286 0.44161201 0.36539609 0.89885367]
 [0.59964769 0.10715072 0.05682158 0.11849717]]
[[0.1885186  0.20341216 0.95757536 0.13021489]
 [0.71416468 0.89515228 0.43261171 0.75969078]
 [0.81249267 0.45263387 0.76443202 0.01478671]
 [0.1609847  0.63047866 0.29632515 0.28678304]
 [0.39238509 0.3436678  0.28314179 0.43021446]
 [0.46449994 0.64267685 0.58142085 0.16227352]
 [0.78562584

[[0.29920876 0.95070427 0.26275122 0.38596501]
 [0.63038467 0.36144915 0.53008594 0.85251654]
 [0.52108694 0.40576811 0.57567059 0.30518432]
 [0.98601551 0.09299024 0.53375907 0.85357157]
 [0.29168931 0.71808245 0.99019278 0.116237  ]
 [0.3908001  0.29485551 0.45057575 0.05255054]
 [0.47139543 0.68576389 0.47266369 0.35670666]
 [0.57571953 0.01137378 0.38996872 0.91823558]
 [0.04613406 0.51599366 0.50897392 0.15893858]
 [0.09793037 0.41590307 0.54897434 0.4776443 ]
 [0.06032478 0.80476675 0.93520741 0.87324941]
 [0.51456719 0.91600582 0.72598044 0.44520006]
 [0.99958457 0.077064   0.52981988 0.13501569]
 [0.10702769 0.20375234 0.56849752 0.09568454]
 [0.10929867 0.85055484 0.41934279 0.4967673 ]]
[[0.24749618 0.38119886 0.96862478 0.89873426]
 [0.76683639 0.01518835 0.54748391 0.8089376 ]
 [0.98842776 0.75989225 0.75312718 0.04432619]
 [0.93736712 0.19744009 0.37500062 0.852448  ]
 [0.6977235  0.76464178 0.58758605 0.23982715]
 [0.93954385 0.21007806 0.04489255 0.01291401]
 [0.15867436

[[0.38588096 0.67347042 0.40137196 0.315655  ]
 [0.14624362 0.90445938 0.36481953 0.17806398]
 [0.5419139  0.22681346 0.95800355 0.10479931]
 [0.50140432 0.57232062 0.26649478 0.72014507]
 [0.93088758 0.25892687 0.58394718 0.59438601]
 [0.61128174 0.69683725 0.00820075 0.17780703]
 [0.47835911 0.27710281 0.73151104 0.13128519]
 [0.49864638 0.62018204 0.19770369 0.80789081]
 [0.93862624 0.76205931 0.46625356 0.63699688]
 [0.81822701 0.2126121  0.74935404 0.36797403]
 [0.30881072 0.59251126 0.83424977 0.25714866]
 [0.3202097  0.86106511 0.07072626 0.35240939]
 [0.97973191 0.32179277 0.24344737 0.95324697]
 [0.24295917 0.30590535 0.66695895 0.12769184]
 [0.48244637 0.14236539 0.61540586 0.75517727]]
[[4.96194061e-01 8.52847169e-01 3.19491079e-01 5.80249288e-01]
 [4.48715168e-01 3.05459946e-01 3.38392243e-01 2.89761507e-01]
 [1.86905898e-01 9.51494233e-01 3.41132756e-01 9.71510776e-01]
 [6.16601794e-01 2.08657267e-01 7.00261178e-02 7.00410949e-01]
 [7.24758967e-01 3.95889982e-01 5.98137255

[[0.69740499 0.72480097 0.35919468 0.65727129]
 [0.71155057 0.20492673 0.54432556 0.84796904]
 [0.66530884 0.77047743 0.916245   0.00924177]
 [0.2297707  0.22736877 0.7609993  0.81981753]
 [0.55384646 0.15618626 0.30131674 0.41574539]
 [0.8801809  0.60355847 0.61021416 0.16599497]
 [0.97617561 0.30801834 0.78903745 0.26702374]
 [0.78889918 0.62842512 0.25561236 0.88194422]
 [0.57155924 0.70058757 0.4519604  0.99485579]
 [0.69340247 0.30526083 0.17372015 0.01274372]
 [0.0835036  0.08541087 0.21379969 0.88685286]
 [0.60406847 0.13118433 0.36647023 0.11892838]
 [0.51100522 0.19645752 0.9765677  0.50102742]
 [0.29615971 0.73860214 0.11610341 0.80558515]
 [0.24297874 0.14145297 0.18023702 0.58289324]]
[[0.87956331 0.45764818 0.4717361  0.27880637]
 [0.30983935 0.99352225 0.27782117 0.93741088]
 [0.32243494 0.72421236 0.25795128 0.27744611]
 [0.92658809 0.79760726 0.87578125 0.62512299]
 [0.41265687 0.83107722 0.06251199 0.03267039]
 [0.69271197 0.09063795 0.03169503 0.83577727]
 [0.25544148

[[0.20412204 0.93947965 0.67326582 0.59903879]
 [0.72866621 0.01139683 0.69055183 0.82597824]
 [0.02171981 0.53163453 0.86284667 0.9309298 ]
 [0.17889244 0.20084424 0.24156931 0.79958559]
 [0.72432585 0.48285863 0.62891877 0.0399052 ]
 [0.85498559 0.76397594 0.05537278 0.29645597]
 [0.32824062 0.86615328 0.69312238 0.85694137]
 [0.15355273 0.60337914 0.30771369 0.28775692]
 [0.9488217  0.49902047 0.01735799 0.01200271]
 [0.45231024 0.84812793 0.09187087 0.7357914 ]
 [0.27590881 0.40115293 0.85211852 0.3192469 ]
 [0.78851279 0.82187481 0.66802506 0.90411603]
 [0.67645877 0.81028315 0.15453139 0.7298929 ]
 [0.62543154 0.00637766 0.99320086 0.3500045 ]
 [0.06276254 0.16808451 0.25186014 0.35323471]]
[[0.70719802 0.77956232 0.99414575 0.17417253]
 [0.28691835 0.8835597  0.77230965 0.92588472]
 [0.87920798 0.38577807 0.95336401 0.82359472]
 [0.90764487 0.5690453  0.71507338 0.89182777]
 [0.54314023 0.13583601 0.78293895 0.52553937]
 [0.01720803 0.9740445  0.12880998 0.951204  ]
 [0.89191343

[[0.90399852 0.71451155 0.5244604  0.38717579]
 [0.05700135 0.79252093 0.94758555 0.56547264]
 [0.67094899 0.11209387 0.41460453 0.47356517]
 [0.15897314 0.68014443 0.90849531 0.506619  ]
 [0.86441563 0.62719857 0.44814709 0.4950213 ]
 [0.72863937 0.03795874 0.33593419 0.6750358 ]
 [0.68894233 0.2187737  0.19705847 0.82781744]
 [0.59473093 0.40111148 0.11105088 0.48832132]
 [0.72798929 0.3022077  0.84448332 0.15690702]
 [0.16056167 0.07398962 0.81583785 0.28395669]
 [0.72486806 0.47222199 0.76199289 0.5346101 ]
 [0.06431028 0.38863074 0.4356235  0.29706393]
 [0.51415513 0.11573719 0.32405449 0.93414335]
 [0.99264452 0.46329557 0.42544152 0.47130355]
 [0.51050516 0.45026191 0.71541225 0.71650599]]
[[0.12375517 0.17019679 0.5354368  0.66878171]
 [0.35939285 0.8925269  0.09502973 0.65624961]
 [0.16603635 0.82777873 0.53680779 0.52871417]
 [0.60694863 0.70530362 0.95355073 0.74817451]
 [0.29826661 0.44645576 0.36012661 0.62588665]
 [0.39217296 0.04115659 0.92330057 0.40623497]
 [0.94428218

[[0.16875278 0.04955014 0.16442062 0.31807057]
 [0.67786142 0.78916925 0.61317993 0.16373795]
 [0.6776638  0.70136971 0.91683656 0.25312356]
 [0.68146991 0.98614385 0.445856   0.7608665 ]
 [0.11683662 0.67169066 0.13107498 0.74225098]
 [0.49911645 0.54338241 0.88152641 0.62700574]
 [0.4128841  0.44158987 0.54225995 0.66425701]
 [0.07708828 0.70199913 0.45592149 0.06563037]
 [0.39816423 0.97932744 0.14145806 0.13037996]
 [0.41372941 0.9193679  0.74026784 0.12249322]
 [0.71874419 0.54413765 0.78008899 0.87948352]
 [0.52527989 0.21877352 0.05209823 0.97707561]
 [0.81637961 0.99568201 0.85389911 0.1131445 ]
 [0.91301392 0.13191815 0.35759895 0.40655209]
 [0.01999314 0.1136116  0.91241285 0.91184485]]
[[0.86244296 0.14428274 0.30864918 0.26477599]
 [0.64804566 0.83820946 0.93524754 0.33779023]
 [0.365447   0.78947798 0.47947488 0.87642653]
 [0.43020146 0.97767683 0.53490846 0.71011972]
 [0.37497705 0.56372963 0.93967276 0.15803352]
 [0.97745399 0.55903913 0.84772777 0.56703028]
 [0.54638699

[[0.1233918  0.2710017  0.48732674 0.37315921]
 [0.31428564 0.80150564 0.00824437 0.53543755]
 [0.47545348 0.68556511 0.6020545  0.19962729]
 [0.13223315 0.03358827 0.21639194 0.30454574]
 [0.924337   0.38316819 0.54672494 0.31818208]
 [0.71533646 0.90296718 0.50533938 0.62402014]
 [0.07255574 0.71396997 0.09503874 0.92404477]
 [0.2776273  0.93888675 0.62002005 0.21322723]
 [0.89414427 0.14497952 0.13209836 0.4485675 ]
 [0.24910299 0.53393827 0.44501244 0.93339027]
 [0.09413365 0.08598807 0.34980023 0.74671549]
 [0.9816364  0.18263239 0.12644944 0.02500395]
 [0.00591715 0.29700479 0.78528996 0.92467738]
 [0.99269504 0.9235711  0.12468582 0.72799162]
 [0.21300234 0.23450152 0.73255942 0.94981092]]
[[0.99805963 0.04283952 0.21140308 0.0124996 ]
 [0.92336595 0.43502965 0.78267279 0.59099616]
 [0.29425898 0.07176462 0.15801587 0.71069466]
 [0.11862925 0.89707509 0.59052743 0.26828062]
 [0.38849428 0.82463969 0.67412661 0.48525598]
 [0.7288107  0.6939172  0.11140349 0.43680183]
 [0.49914634

[[0.09458763 0.9649889  0.56406067 0.0009968 ]
 [0.82788457 0.22182932 0.27132311 0.59592551]
 [0.11761452 0.92429189 0.65936145 0.34349391]
 [0.73611239 0.86309629 0.832586   0.58902119]
 [0.80382819 0.16107392 0.62576839 0.35378386]
 [0.30354126 0.14518191 0.03976475 0.01889631]
 [0.87679235 0.68504007 0.6761026  0.60065659]
 [0.38265833 0.35303992 0.2778667  0.3428464 ]
 [0.70943227 0.493085   0.75323752 0.09308263]
 [0.49821854 0.3868406  0.0180043  0.1654201 ]
 [0.09123717 0.3562719  0.7182626  0.64547754]
 [0.60287312 0.49660064 0.08614292 0.54783135]
 [0.21456186 0.84845717 0.2090218  0.82667207]
 [0.56074229 0.38045218 0.26201342 0.5161999 ]
 [0.58035163 0.14677125 0.98593202 0.17655253]]
[[0.70979316 0.97779525 0.97743358 0.75919298]
 [0.93352102 0.76489811 0.62858148 0.21364572]
 [0.0806799  0.04107927 0.41974928 0.58935893]
 [0.40948839 0.73647256 0.52031735 0.28294218]
 [0.95103509 0.38931651 0.11724421 0.78941193]
 [0.19815638 0.09814696 0.65055254 0.75047951]
 [0.05244656

[[0.3429661  0.40177029 0.51071742 0.63212936]
 [0.2812844  0.44047964 0.1063274  0.47404548]
 [0.99341085 0.10372718 0.26484651 0.7057884 ]
 [0.42063435 0.52148894 0.48252065 0.90133802]
 [0.65107272 0.49417366 0.41869555 0.91334865]
 [0.44034534 0.46985081 0.66391679 0.02154745]
 [0.00242901 0.8547223  0.36698923 0.14458779]
 [0.45344859 0.52620369 0.85928732 0.54504068]
 [0.82772011 0.15318523 0.63464327 0.14957963]
 [0.24144506 0.04455712 0.94242744 0.97139299]
 [0.56070204 0.08947816 0.92748329 0.02724952]
 [0.52515321 0.50672028 0.01526915 0.41227731]
 [0.4063062  0.36377245 0.98389599 0.56129531]
 [0.5313229  0.77773286 0.28925995 0.92536168]
 [0.33247949 0.99965036 0.42362269 0.74687323]]
[[0.59362049 0.60989143 0.19376141 0.54990598]
 [0.3524885  0.94882296 0.90628101 0.06361606]
 [0.98154536 0.21054756 0.56294928 0.20284574]
 [0.50895953 0.21144619 0.91278492 0.53268495]
 [0.76950879 0.13287264 0.08171775 0.6969968 ]
 [0.38387057 0.86604662 0.12343059 0.89421237]
 [0.62819105

[[0.6877883  0.16483443 0.08221004 0.04615682]
 [0.00584221 0.20197165 0.68895888 0.05398447]
 [0.87245116 0.63669672 0.91312135 0.02399938]
 [0.68111887 0.98611884 0.37677777 0.42596159]
 [0.81329209 0.37916708 0.83245332 0.60235627]
 [0.40371676 0.14596414 0.95961288 0.25348914]
 [0.22054419 0.08221012 0.62689525 0.38177164]
 [0.12653743 0.66632396 0.70375824 0.12514493]
 [0.82346319 0.80454579 0.94916243 0.11447251]
 [0.84566177 0.07448547 0.8825059  0.5801293 ]
 [0.94689214 0.18005406 0.77203266 0.60886996]
 [0.67055304 0.39375626 0.17944958 0.99684203]
 [0.83111784 0.29128722 0.5059304  0.7027245 ]
 [0.22786827 0.30059899 0.90823392 0.40730069]
 [0.40507363 0.98186184 0.14739328 0.10974322]]
[[0.63648465 0.82317153 0.45888412 0.39607273]
 [0.79971108 0.60647092 0.05255456 0.21317813]
 [0.80810782 0.05035522 0.50893047 0.80543173]
 [0.98392029 0.1656895  0.99227128 0.70124137]
 [0.11867727 0.95231318 0.84579946 0.68074204]
 [0.88062267 0.89224558 0.42940475 0.32115432]
 [0.78784375

[[0.79627736 0.70799639 0.7135748  0.92419481]
 [0.26392836 0.34788509 0.12778831 0.41704913]
 [0.67932938 0.09906151 0.80535394 0.74285186]
 [0.20686557 0.60232302 0.8530402  0.00506499]
 [0.18221161 0.24269512 0.67305625 0.61511979]
 [0.40848716 0.43110828 0.72322531 0.57079716]
 [0.45888122 0.01814167 0.92174275 0.15855309]
 [0.0426244  0.73046648 0.81573487 0.40754701]
 [0.57826286 0.28703052 0.96666766 0.67405352]
 [0.21965207 0.37173765 0.04339664 0.38943399]
 [0.95566921 0.21984764 0.55493139 0.8788098 ]
 [0.91242611 0.48614595 0.76290413 0.92159963]
 [0.43755874 0.90283694 0.88119394 0.92862734]
 [0.91495466 0.30989408 0.04791757 0.89915897]
 [0.39852933 0.62656905 0.33076755 0.48919391]]
[[0.77018053 0.83501844 0.45013852 0.6478881 ]
 [0.83284245 0.82387619 0.53222227 0.84366123]
 [0.67831917 0.37717167 0.79202256 0.39220716]
 [0.06722536 0.91727209 0.93854438 0.97764939]
 [0.65700985 0.68261492 0.08641526 0.75510767]
 [0.62373956 0.71203495 0.12747203 0.2703071 ]
 [0.89873141

[[0.94566426 0.04128644 0.12875216 0.92367475]
 [0.00916997 0.71964074 0.63411261 0.74590759]
 [0.05849234 0.23348039 0.5351654  0.71567793]
 [0.77918483 0.71445427 0.77463951 0.17337694]
 [0.58351197 0.57956127 0.66825175 0.72811191]
 [0.08997584 0.07736712 0.28377934 0.35906918]
 [0.07448442 0.3519404  0.84264587 0.14537139]
 [0.9474896  0.32009347 0.53652548 0.11822846]
 [0.02358892 0.76405094 0.91585039 0.39132075]
 [0.03542326 0.5873282  0.8251834  0.34961982]
 [0.5283934  0.35212477 0.89446217 0.60700965]
 [0.18666473 0.48014945 0.88332124 0.69708147]
 [0.74865299 0.08526417 0.97149911 0.7311764 ]
 [0.85862362 0.75881599 0.72567135 0.57922806]
 [0.22458747 0.08819059 0.65277223 0.21148683]]
[[0.30691714 0.42004156 0.24848029 0.77629478]
 [0.09100672 0.58210026 0.33771796 0.72226121]
 [0.47135804 0.22172549 0.29474885 0.06306118]
 [0.00814454 0.22847609 0.06351203 0.35338326]
 [0.63980092 0.68746019 0.55603708 0.49537672]
 [0.30959827 0.3420798  0.83124254 0.64871886]
 [0.71773854

[[0.08531258 0.64695006 0.09419979 0.69659377]
 [0.15021618 0.25322328 0.6378098  0.13165411]
 [0.4299998  0.00570989 0.60250017 0.86111125]
 [0.28555826 0.77599509 0.48520874 0.02885518]
 [0.1343878  0.62568959 0.78721105 0.78130471]
 [0.85829087 0.96479507 0.44202108 0.95972272]
 [0.02673334 0.26000789 0.42229412 0.69633194]
 [0.29474085 0.96778103 0.81971813 0.48150252]
 [0.79227816 0.72917487 0.99203285 0.59703165]
 [0.02627839 0.18993807 0.6742158  0.42232492]
 [0.11895162 0.39949558 0.46189709 0.18853207]
 [0.27457388 0.05180284 0.57544343 0.58316835]
 [0.26058085 0.03079313 0.73339248 0.11014426]
 [0.29324713 0.38799445 0.33827944 0.01261688]
 [0.29192304 0.73739834 0.14179932 0.97812701]]
[[0.92973557 0.12868467 0.6785619  0.35270706]
 [0.22457132 0.54782416 0.75573027 0.49452512]
 [0.12022906 0.42225638 0.65024811 0.10946432]
 [0.36883244 0.44601879 0.50486146 0.92475716]
 [0.77272677 0.28060792 0.62082288 0.67315897]
 [0.69873597 0.26508916 0.68887102 0.62376141]
 [0.45097148

[[0.61830283 0.08501799 0.98558675 0.73045115]
 [0.12121359 0.98148521 0.21818166 0.44761892]
 [0.56061191 0.38774371 0.13415925 0.65565835]
 [0.15053994 0.48214626 0.96430045 0.51107602]
 [0.0956354  0.83567011 0.2176148  0.7908234 ]
 [0.62695005 0.92163004 0.57674322 0.4864093 ]
 [0.64668004 0.84416068 0.3013498  0.36772429]
 [0.2145576  0.58937221 0.95622878 0.41961898]
 [0.48568328 0.87288217 0.48834138 0.5928047 ]
 [0.7741627  0.58109269 0.50137928 0.02071966]
 [0.11344942 0.68671164 0.68449485 0.50341587]
 [0.58741393 0.13019849 0.86045983 0.90090046]
 [0.34119887 0.44678935 0.15145027 0.93616563]
 [0.47928672 0.65653682 0.41092966 0.52183323]
 [0.36409127 0.51674402 0.3956681  0.73085478]]
[[0.72728798 0.82286536 0.59778921 0.0321302 ]
 [0.32081537 0.30829205 0.97787799 0.14504485]
 [0.7745507  0.86830516 0.40866218 0.94719168]
 [0.5071523  0.31455125 0.22638028 0.51462371]
 [0.83915188 0.74170145 0.98825315 0.60882295]
 [0.33324841 0.44793546 0.71098723 0.77079612]
 [0.49886366

[[0.79588043 0.89168855 0.67814968 0.06901788]
 [0.8613266  0.07069813 0.02839163 0.29269007]
 [0.58740745 0.93616446 0.52110083 0.90032433]
 [0.800266   0.47804516 0.25516083 0.52309539]
 [0.51258271 0.68015207 0.67206722 0.46242092]
 [0.01506106 0.30425016 0.10742173 0.50970199]
 [0.74813856 0.28348799 0.69412088 0.38431685]
 [0.67186942 0.73207422 0.0995273  0.24856657]
 [0.59298588 0.290416   0.0743115  0.56089212]
 [0.99476714 0.2128829  0.00642095 0.22861519]
 [0.16768565 0.53854789 0.3219835  0.26417663]
 [0.93563452 0.21916913 0.07289059 0.29217128]
 [0.47164861 0.17503646 0.3881959  0.34438648]
 [0.95277814 0.67769081 0.38440889 0.50159543]
 [0.50746998 0.52090089 0.52896345 0.68804278]]
[[0.45342727 0.7376951  0.40029552 0.74124254]
 [0.33388362 0.58707795 0.79238594 0.61025548]
 [0.8289936  0.69447621 0.48933725 0.02383023]
 [0.54820093 0.76650201 0.22891949 0.63446672]
 [0.18829095 0.46105189 0.68133128 0.53962696]
 [0.07523172 0.9310365  0.32896344 0.6035069 ]
 [0.79081369

[[0.20860659 0.00727153 0.90964958 0.11192641]
 [0.49166362 0.98411718 0.04175027 0.62150292]
 [0.04401057 0.55083266 0.28462642 0.26718725]
 [0.44756707 0.71042009 0.56897042 0.59493677]
 [0.29040503 0.76047561 0.03782028 0.90384977]
 [0.93027369 0.01801699 0.22478132 0.34447695]
 [0.33298987 0.47785874 0.87645986 0.88142808]
 [0.99306723 0.12758693 0.00247988 0.8782431 ]
 [0.80374807 0.57457564 0.11914056 0.37892998]
 [0.09124918 0.68990639 0.58078892 0.82948622]
 [0.67468715 0.20701502 0.78571119 0.87546948]
 [0.25521725 0.11490138 0.6630274  0.70682965]
 [0.04808766 0.38236071 0.54976431 0.8622203 ]
 [0.32181578 0.67223143 0.50639037 0.64187449]
 [0.04424272 0.33354039 0.31952851 0.01753768]]
[[0.46743783 0.22107711 0.60482293 0.20674596]
 [0.93072578 0.1335132  0.48327456 0.20391146]
 [0.27275833 0.94525424 0.90164748 0.16839921]
 [0.4140287  0.32244833 0.15492313 0.09070673]
 [0.21969168 0.49683278 0.57548454 0.19595356]
 [0.1224934  0.22921479 0.40272133 0.43984895]
 [0.42084652

[[0.23028685 0.6054663  0.63002456 0.24027492]
 [0.31872039 0.18423958 0.76564821 0.66223876]
 [0.91095734 0.44806421 0.22902193 0.50410098]
 [0.98074904 0.65328025 0.61486949 0.10057433]
 [0.40812451 0.02198034 0.71254825 0.89207041]
 [0.39310177 0.5871068  0.94408374 0.53414496]
 [0.33393564 0.28943515 0.03000194 0.80132815]
 [0.95019163 0.97691437 0.55479346 0.7057828 ]
 [0.06726617 0.99236194 0.80624033 0.03771914]
 [0.1030869  0.14633404 0.4679879  0.87305736]
 [0.37221853 0.85040705 0.15790393 0.09799285]
 [0.95822837 0.6528329  0.2142703  0.48406877]
 [0.05316439 0.46587413 0.86060791 0.94223476]
 [0.73462044 0.46100277 0.29450156 0.11081085]
 [0.54564068 0.30678031 0.35640147 0.14164405]]
[[0.37258212 0.14337973 0.63804302 0.07255205]
 [0.99092554 0.09482376 0.84561981 0.24359734]
 [0.20338261 0.44682594 0.3115378  0.94751468]
 [0.52853422 0.30927511 0.07595846 0.41254088]
 [0.98313677 0.95236255 0.85686838 0.7777086 ]
 [0.18019167 0.7550575  0.82938901 0.23638467]
 [0.8719276 

[[0.96823925 0.31578774 0.45369754 0.47384458]
 [0.28591303 0.28946358 0.33217074 0.73033831]
 [0.7637502  0.85113377 0.67101466 0.43854376]
 [0.00210933 0.83403374 0.41839083 0.53498459]
 [0.43456373 0.84147483 0.83124561 0.32118861]
 [0.94635576 0.97918755 0.34150355 0.24421706]
 [0.83720501 0.69168766 0.82517853 0.38170457]
 [0.29111673 0.52082265 0.74156742 0.2587093 ]
 [0.53451793 0.52794598 0.6541402  0.20566161]
 [0.54063741 0.14366673 0.27130526 0.16219579]
 [0.94914144 0.89939722 0.54258911 0.10079136]
 [0.56882499 0.07359573 0.89546582 0.23448548]
 [0.59294742 0.09947197 0.07048927 0.59393228]
 [0.77955845 0.59354827 0.70946093 0.87702134]
 [0.59766218 0.22572761 0.45019222 0.44400748]]
[[0.64169532 0.06065751 0.35026732 0.60967116]
 [0.4545102  0.88850718 0.65665514 0.49941516]
 [0.5715739  0.88836364 0.16151201 0.36013526]
 [0.26766326 0.43740832 0.03841395 0.88348142]
 [0.33408787 0.86227429 0.11939847 0.36599011]
 [0.06236635 0.03204563 0.21132834 0.68430701]
 [0.25835629

[[0.21934811 0.1568173  0.54893311 0.37770939]
 [0.50730431 0.82047857 0.79330136 0.66053329]
 [0.13619176 0.03733315 0.3353388  0.09320918]
 [0.41540729 0.28058941 0.79033478 0.83922054]
 [0.97795529 0.97070121 0.0215116  0.4107067 ]
 [0.99848633 0.35247573 0.46309437 0.77482014]
 [0.73709644 0.83360917 0.26517631 0.02058388]
 [0.62605171 0.69042777 0.53758529 0.13897403]
 [0.28051359 0.11255692 0.34647093 0.18569383]
 [0.49093526 0.35536351 0.15739719 0.35767802]
 [0.8827913  0.26235998 0.39409041 0.17280813]
 [0.79662955 0.62111751 0.00391825 0.44887951]
 [0.97699692 0.91813031 0.95844318 0.92897596]
 [0.62792283 0.32810998 0.78087493 0.00423733]
 [0.45571552 0.89285165 0.2696475  0.0757085 ]]
[[0.10365102 0.42505379 0.76269917 0.48757048]
 [0.50061482 0.56261929 0.36707506 0.31860036]
 [0.10819826 0.67417629 0.20233629 0.28878553]
 [0.94715751 0.57208434 0.84691027 0.44759465]
 [0.63263025 0.36998147 0.81103724 0.03438122]
 [0.7854339  0.83718575 0.82337944 0.82893334]
 [0.91430825

[[0.86168212 0.95220313 0.28826677 0.01078892]
 [0.49405625 0.06824899 0.26582599 0.79347444]
 [0.7298492  0.72064577 0.02691646 0.45965571]
 [0.17641815 0.87786515 0.79844014 0.08010308]
 [0.69275427 0.57324423 0.26654329 0.80433892]
 [0.95443889 0.04367019 0.47834765 0.41158014]
 [0.9631415  0.53533483 0.4198839  0.0622449 ]
 [0.28448244 0.06760904 0.60338899 0.74820808]
 [0.57233077 0.91813213 0.59242066 0.42787837]
 [0.28945925 0.3290741  0.23493878 0.76269542]
 [0.17784266 0.17237426 0.08132322 0.31606624]
 [0.35079145 0.58158936 0.74489179 0.57421146]
 [0.57486369 0.89571275 0.36725307 0.94167152]
 [0.16568101 0.03966088 0.67490808 0.15039694]
 [0.69795432 0.57022225 0.21557965 0.39246478]]
[[0.5064459  0.4052265  0.93919457 0.87952949]
 [0.6800866  0.27583937 0.00784385 0.97888766]
 [0.98405621 0.32841131 0.88178677 0.54433982]
 [0.82081107 0.93950091 0.3248486  0.80652905]
 [0.71813285 0.65835961 0.16086113 0.99065218]
 [0.31869888 0.85390904 0.57225227 0.16793702]
 [0.40383177

[[0.96503278 0.07731355 0.13053471 0.35373281]
 [0.51898368 0.60877635 0.04064148 0.7269944 ]
 [0.61052641 0.6753018  0.54490664 0.90717212]
 [0.72723792 0.73180491 0.60034909 0.4358914 ]
 [0.98142117 0.30618792 0.95349441 0.72959463]
 [0.05415631 0.72773259 0.38895717 0.74943906]
 [0.23931438 0.95543374 0.67374632 0.52626962]
 [0.45011909 0.89351003 0.64266411 0.81873832]
 [0.8020514  0.40589052 0.74007197 0.16939835]
 [0.28212368 0.73311485 0.8623966  0.28201724]
 [0.72409474 0.85401172 0.94794604 0.33957777]
 [0.14702213 0.8523242  0.1860048  0.14666208]
 [0.92990309 0.69062583 0.63196769 0.76941512]
 [0.53413683 0.78058674 0.69132619 0.61094987]
 [0.22166178 0.12055847 0.94735328 0.49929837]]
[[0.43745877 0.48204265 0.05140024 0.06353678]
 [0.36274779 0.95790621 0.04000977 0.45665526]
 [0.33635909 0.39191429 0.25895594 0.22777972]
 [0.13971417 0.28426157 0.85832439 0.61460525]
 [0.82363347 0.78007211 0.4679997  0.71052545]
 [0.8275096  0.38180443 0.38827178 0.49939258]
 [0.09067702

[[0.88534527 0.28327923 0.68092334 0.97206235]
 [0.07439443 0.11488542 0.5743016  0.91290479]
 [0.32044026 0.85154823 0.1003847  0.61442124]
 [0.90825552 0.35382754 0.19266124 0.97769456]
 [0.00634992 0.78226832 0.07327668 0.81043628]
 [0.49844407 0.82904498 0.03343076 0.75386687]
 [0.44327018 0.20436455 0.18899482 0.79064474]
 [0.66701111 0.657605   0.52913291 0.54029299]
 [0.23828647 0.94591123 0.04265601 0.687844  ]
 [0.01791824 0.62201349 0.27941231 0.98579146]
 [0.15073485 0.72829149 0.42748267 0.22477931]
 [0.8942363  0.09729541 0.24156245 0.89906115]
 [0.7021793  0.96523478 0.09045659 0.70597611]
 [0.06393988 0.34953925 0.51087664 0.84554625]
 [0.77597574 0.95344649 0.20039203 0.56543225]]
[[0.28794821 0.87828266 0.56667037 0.15192268]
 [0.15104076 0.97519395 0.12917543 0.23832445]
 [0.25984507 0.90465872 0.57290764 0.23049795]
 [0.98531749 0.20801795 0.17216151 0.91331352]
 [0.39326592 0.7504195  0.93971172 0.47074486]
 [0.97495476 0.87590531 0.3302584  0.33622724]
 [0.84208138

[[0.54059898 0.99110811 0.66111562 0.6584851 ]
 [0.8796598  0.36721608 0.46513722 0.26690836]
 [0.19815784 0.53533053 0.66605848 0.56172478]
 [0.35234021 0.84109384 0.15034692 0.11270335]
 [0.61896164 0.07100092 0.96777203 0.91978209]
 [0.36221066 0.84729439 0.08034477 0.07660656]
 [0.54918601 0.55425359 0.4060225  0.78414953]
 [0.10891744 0.90953483 0.02928455 0.80128354]
 [0.55678699 0.62725822 0.10894238 0.23039582]
 [0.7346246  0.64368542 0.81245765 0.52684894]
 [0.20759543 0.0991128  0.54323813 0.32170049]
 [0.63929619 0.31520324 0.4525042  0.62890032]
 [0.18903002 0.51862684 0.0353764  0.19511456]
 [0.40866221 0.65000905 0.55738383 0.17421744]
 [0.8380166  0.79877416 0.34943515 0.12292109]]
[[0.27555452 0.82385689 0.80599122 0.96386981]
 [0.14686967 0.22209008 0.47052878 0.17830485]
 [0.49804612 0.78227009 0.25424495 0.07370566]
 [0.3614242  0.19039513 0.90152444 0.40913824]
 [0.47750197 0.50040787 0.28505338 0.96223176]
 [0.67428931 0.81447473 0.25660946 0.38076908]
 [0.44312822